# Generated for envman. Do not edit.
test -s "$HOME/.config/envman/load.fish" ; and source "$HOME/.config/envman/load.fish"
test -s "$HOME/.config/envman/functions.fish" ; and source "$HOME/.config/envman/functions.fish"

test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish

# added by Webi for pyenv
status is-login ; and pyenv init --path | source
status is-interactive ; and pyenv init - | source

# Generated by Webi. Do not edit.
webi --init fish | source
